# Configuration of the CI pipeline
name: 'Stack Magento'
canonical: 'stack-magento'
description: 'Description of the stack magento'
keywords:
  - 'stack'
  - 'public'
author: 'gaelL'
image: 'https://raw.githubusercontent.com/cycloid/test-psc/stack-magento/master/icon.png'
type: 'stack'
technologies:
  - technology: 'mysql'
    version: '5.x'
  - technology: 'Nginx'
    version: '1.1x'
dependencies:
  - ref: 'cycloid:stack-infrastructure'
    required: true
  - ref: 'cycloid:infra-amazon-s3'
    required: true
  - ref: 'cycloid:stack-ses'
    required: false
config:
  pipeline:
    pipeline:
      path: 'pipeline/magento.yml'
    variables:
      path: 'pipeline/variables.sample.yml'

  # Configuration of ansible for provisionning
  ansible:
    magento:
      path: 'ansible/environments/front.yml.sample'
      destination: 'ansible/environments/($ environment $)-front.yml'

  # Configuration of terraform to setup the infrastructure    
  terraform:
    magento:
      path: 'terraform/magento.tf.sample'
      destination: 'terraform/magento/($ environment $)/magento.tf'
