# Configuration of the Cycloid stack
version: '4'
name: 'stack-templating-sharing'
canonical: 'stack-templating-sharing'
description: 'To test terraform and templating technology using the same form values.'
keywords:
  - 'kubernetes'
  - 'templating'
author: 'Cycloid'
image: 'https://raw.githubusercontent.com/cycloidio/backend-test-catalogs-repo/refs/heads/test-e2e/stack-templating/icon.png'
type: 'stack'
technologies:
  - technology: Kubernetes
    version: 1.15+
config:
  tech-sharing:
    name: 'Tech Sharing'
    description: "Testing that tech sharing between terraform and templating won't collapse"
    terraform:
      main:
        path: 'main.tf.sample'
        destination: "($ .config_root $)/terraform/main.tf"
    templating:
      var_path: '($ .config_root $)/vars/template-files.json'
      templates:
      - paths:
        - template.yaml.tmpl
        destination: ($ .config_root $)/hello_world.yaml
        config:
          destination_is_file: true
