---
use_cases:
  - name: tech-sharing
    sections:
      - name: "section"
        groups:
          - name: "group"
            technologies: [custom, terraform]
            vars:
              - name: "message"
                key: "module.hello_world.message"
                widget: "simple_text"
                type: "string"
                default: "hello world!"
