# Configuration of the Cycloid stack
version: "4"
name: "stack-templating"
canonical: "stack-templating"
description: "Used to execute kubernetes template files."
keywords:
  - "kubernetes"
  - "templating"
author: "Cycloid"
image: "https://raw.githubusercontent.com/cycloidio/backend-test-catalogs-repo/refs/heads/test-e2e/stack-templating/icon.png"
type: "stack"
technologies:
  - technology: Kubernetes
    version: 1.15+
config:
  template-files:
    name: "Template files"
    description: "Template files given in paths"
    custom:
      var_path: "templating/vars/template-files.json"
      templates:
        - paths:
            - templating/source-templates/deployment.yaml.tmpl
          helpers:
            - templating/helpers
          destination: templating/result/template-files/deployment.yaml
          config:
            destination_is_file: true
        - paths:
            - templating/source-templates/dir1/service.yaml.tmpl
          helpers:
            - templating/helpers
          destination: templating/result/template-files
  template-dir:
    name: "Template directory"
    description: "Template directory given in paths"
    custom:
      var_path: "templating/vars/template-dir.json"
      templates:
        - paths:
            - templating/source-templates
          helpers:
            - templating/helpers
          destination: templating/result/template-dir/onefile/manifest.yaml
          config:
            destination_is_file: true
        - paths:
            - templating/source-templates
          helpers:
            - templating/helpers
          destination: templating/result/template-dir/tree
          config:
            destination_is_file: false
