---
version: 2
use_cases:
  - name: template-files
    sections:
      - name: Template variables
        groups:
          - name: nginx
            technologies: [templating]
            vars:
              - name: Image tag
                key: nginx.image_tag
                type: string
                widget: simple_text
                required: true

              - name: Container port
                key: nginx.container_port
                type: integer
                widget: number
                default: 80

              - name: Number of replicas
                key: replicas_num
                type: integer
                widget: number
                default: 2
  - name: template-dir
    sections:
      - name: Template variables
        groups:
          - name: nginx
            technologies: [templating]
            vars:
              - name: Image tag
                key: nginx.image_tag
                type: string
                widget: simple_text
                required: true

              - name: Container port
                key: nginx.container_port
                type: integer
                widget: number
                default: 80

              - name: Number of replicas
                key: replicas_num
                type: integer
                widget: number
                default: 2
