version: 4
name: SimpleV4 with Hooks
canonical: simplev4-with-hooks
author: "lukasz_opasiak_cycloid"
description: "Simple pipeline config with hooks."
image: https://github.com/cycloidio/bootstrap-stacks/blob/master/blank-sample/thumbnail.png
template: false
status: "public"
config:
  hooks_jobs:
    name: "Jobs"
    pipeline:
      pipeline:
        path: "pipeline/pipeline.yml"
        hooks:
          on_create: job:on-pipeline-created
          on_update: job:on-pipeline-updated
          on_delete: job:on-pipeline-deleted
      variables:
        path: "pipeline/variables.sample.yml"
        destination: "($ .project $)/pipeline/($ .environment $)/variables-($ .component $).yml"

  hooks_resources:
    name: "Resources"
    pipeline:
      pipeline:
        path: "pipeline/pipeline-resources.yml"
        hooks:
          on_create: resource:on-create-resource
          on_update: resource:on-update-resource
          on_delete: resource:on-delete-resource
      variables:
        path: "pipeline/variables.sample.yml"
        destination: "($ .project $)/pipeline/($ .environment $)/variables-($ .component $).yml"
