# Define the stack configuration form and organize inputs of various types into sections and groups.
# See: https://docs.staging.cycloid.io/deploy/stackforms/file-format.html
use_cases:
  - name: hooks_jobs
    sections:
      - name: Example section
        groups:
          - name: Example group
            technologies: [pipeline]
            vars:
              - name: "Notify URL"
                description: "Notify URL for pipeline hooks."
                key: notify_url
                type: string
                widget: simple_text
                required: true
  - name: hooks_resources
    sections:
      - name: Example section
        groups:
          - name: Example group
            technologies: [pipeline]
            vars:
              - name: "Notify URL"
                description: "Notify URL for pipeline hooks."
                key: notify_url
                type: string
                widget: simple_text
                required: true
  - name: hooks_pausing
    sections:
      - name: Example section
        groups:
          - name: Example group
            technologies: [pipeline]
            vars:
              - name: "Notify URL"
                description: "Notify URL for pipeline hooks."
                key: notify_url
                type: string
                widget: simple_text
                required: true
