first-usecase:
  pipeline:
    group1:
    - widget: "text_area"
      default: "nobucket"
      type: "string"
      description: "Bucket used to store magento code"
      key: "magento_deploy_bucket_name"
      name: "The bucket used"
    - widget: "text_area"
      type: "string"
      description: "Doesn't matter"
      key: "no-exist"
      name: "Some imaginary var"
  terraform:
    group2:
    - widget: "text_area"
      type: "boolean"
      key: "rds_multiaz"
      name: "RDS multi-AZ"
      required: true
    - widget: "slider_range"
      type: "integer"
      default: 2
      values: [1, 10]
      key: "rds_backup_retention"
      name: "Backup retention"
      required: true
    - widget: "number"
      type: "integer"
      key: "front_count"
      name: "Front amount"
      required: true
    - widget: "text_area"
      type: "array"
      description: "List of public network IDs"
      key: "public_subnets_ids"
      name: "Pub nets"
    - widget: "text_area"
      type: "string"
      description: "The VPC ID to run the project"
      key: "vpc_id"
      name: "VPC ID"
    - widget: "slider_list"
      required: true
      default: "XS"
      unit: "($, GHz, GB)"
      type: "map"
      values: [{label: XS, value: t3.micro}, {label: S, value: t3.small}, {label: M, value: t3.medium}, {label: L, value: t3.large}]
      description: ""
      key: "instance_type"
      name: "mapped variable"
      quota_config:
        mapping:
          t3.micro: "2 cpu, 2 memory"
          t3.small: "3 cpu, 3 memory"
          t3.medium: "3 cpu, 3 memory"
          t3.large: "4 cpu, 4 memory"
        count_ref: "front_count"
    - widget: "number"
      type: "integer"
      key: "storage"
      name: "Front storage"
      quota_config:
        type: "storage"
        count_ref: "front_count"
    - widget: "cy_inventory_resource"
      type: "integer"
      key: "inventory_test"
      name: "Inventory test"
      widget_config:
        attribute: "id"
        filters:
          type: "aws_vpc"
  terragrunt:
    group3:
    - widget: "number"
      type: "integer"
      key: "allocated_storage"
      name: "Front storage"
second-usecase:
  ansible:
    groupY:
    - widget: "dropdown"
      values: [{foo: bar}, {bar: foo}]
      type: "map"
      name: "Magento Map"
      key: "magento_map"
      required: true
  terraform:
    groupX:
    - widget: "simple_text"
      default: ""
      type: "string"
      description: "The DB password for Magento"
      key: "rds_password"
      name: "RDS password"
imaginary-use-case:
  ansible:
    group1:
    - widget: "simple_text"
      default: "don't matter"
      type: "string"
      description: "Some stuff"
      key: "var"
      name: "var with imaginary friends"
